// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCrg0roDGlVBBsrFt7z5RFjcgrf6UEksAM',
    appId: '1:642813048864:web:7ce1fbc0d111034c1fa445',
    messagingSenderId: '642813048864',
    projectId: 'benlekal',
    authDomain: 'benlekal.firebaseapp.com',
    storageBucket: 'benlekal.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJ3WBHqY_v2fIafrZJnF7Keo_JFPf3J2M',
    appId: '1:642813048864:android:b2144420debf386e1fa445',
    messagingSenderId: '642813048864',
    projectId: 'benlekal',
    storageBucket: 'benlekal.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDcjPFMteTSTCDNx2OdYV6Tv08gWYP0udc',
    appId: '1:642813048864:ios:32b29eee6b67fd121fa445',
    messagingSenderId: '642813048864',
    projectId: 'benlekal',
    storageBucket: 'benlekal.appspot.com',
    iosBundleId: 'com.example.psychologyApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDcjPFMteTSTCDNx2OdYV6Tv08gWYP0udc',
    appId: '1:642813048864:ios:32b29eee6b67fd121fa445',
    messagingSenderId: '642813048864',
    projectId: 'benlekal',
    storageBucket: 'benlekal.appspot.com',
    iosBundleId: 'com.example.psychologyApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCrg0roDGlVBBsrFt7z5RFjcgrf6UEksAM',
    appId: '1:642813048864:web:52ebfcc3907862d71fa445',
    messagingSenderId: '642813048864',
    projectId: 'benlekal',
    authDomain: 'benlekal.firebaseapp.com',
    storageBucket: 'benlekal.appspot.com',
  );
}
